name: Download MaxMind GeoLite2 Databases

on:
  schedule:
    - cron: '0 0 * * *'  # 每日 00:00 UTC 运行
  workflow_dispatch:      # 允许手动触发

permissions:
  contents: write   # ⚠️ 关键：赋予 push 权限

jobs:
  download-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up dependencies
        run: sudo apt-get update && sudo apt-get install -y wget tar

      - name: Download GeoLite2-Country
        run: |
          wget -O GeoLite2-Country.tar.gz "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country&license_key=${{ secrets.MAXMIND_LICENSE_KEY }}&suffix=tar.gz"
          tar -xzf GeoLite2-Country.tar.gz
          find . -name "*.mmdb" -exec mv {} ./GeoLite2-Country.mmdb \;
          rm -rf GeoLite2-Country.tar.gz
          find . -type d -name "GeoLite2-Country_*" -exec rm -rf {} +

      - name: Download GeoLite2-City
        run: |
          wget -O GeoLite2-City.tar.gz "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key=${{ secrets.MAXMIND_LICENSE_KEY }}&suffix=tar.gz"
          tar -xzf GeoLite2-City.tar.gz
          find . -name "*.mmdb" -exec mv {} ./GeoLite2-City.mmdb \;
          rm -rf GeoLite2-City.tar.gz
          find . -type d -name "GeoLite2-City_*" -exec rm -rf {} +

      - name: Download GeoLite2-ASN
        run: |
          wget -O GeoLite2-ASN.tar.gz "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-ASN&license_key=${{ secrets.MAXMIND_LICENSE_KEY }}&suffix=tar.gz"
          tar -xzf GeoLite2-ASN.tar.gz
          find . -name "*.mmdb" -exec mv {} ./GeoLite2-ASN.mmdb \;
          rm -rf GeoLite2-ASN.tar.gz
          find . -type d -name "GeoLite2-ASN_*" -exec rm -rf {} +

      - name: Commit and push mmdb files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add *.mmdb
          git commit -m "Update GeoLite2 databases [Auto]" || echo "No changes to commit"
          git push

      - name: Upload GeoLite2-Country.mmdb to Gist
        uses: exuanbo/actions-create-or-update-gist@v1
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: ${{ secrets.GIST_ID }}
          file_path: GeoLite2-Country.mmdb
          file_name: GeoLite2-Country.mmdb

      - name: Upload GeoLite2-City.mmdb to Gist
        uses: exuanbo/actions-create-or-update-gist@v1
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: ${{ secrets.GIST_ID }}
          file_path: GeoLite2-City.mmdb
          file_name: GeoLite2-City.mmdb

      - name: Upload GeoLite2-ASN.mmdb to Gist
        uses: exuanbo/actions-create-or-update-gist@v1
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: ${{ secrets.GIST_ID }}
          file_path: GeoLite2-ASN.mmdb
          file_name: GeoLite2-ASN.mmdb
